### ISSUE TITLE
Compilation error on main branch

### ISSUE THREAD

**Issue by charlio23** [markvdw/mml-autumn-2022#16]
when compiling the main branch on overleaf or TexMaker, the following compilation error is raised.

in answers-lecture2-diff.tex line 5

Undefined control sequence.
The compiler is having trouble understanding a command you have used. Check that the command is spelled correctly. If the command is part of a package, make sure you have included the package in your preamble using \usepackage{...}.

<recently read> \rank 
                      
l.5 ...certainly won't be if $M > N$, since $\rank
                                                   \Phi(X)\transpose\Phi(X) ...
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.

**Comment by markvdw** [comment]
Thanks for noting. I've fixed this.
