### ISSUE TITLE
Q17 minor error in Hessian derivation

### ISSUE THREAD

**Issue by charlio23** [markvdw/mml-autumn-2022#43]
Hello,

In Q17, the last inequality has a final step that seems odd. It's the following.

$$ - (\sum_{i=1}^N  {(x_i - \mu^* ))}^2  \geq -  \sum_{i=1}^N {(x_i - \mu^* )}^2 $$

Indeed, this is true because 
 $$\sum_{i=1}^N (x_i - \mu^*) = 0$$
so it is clearly greater or equal than something negative.

In case I am not missing anything, could we fix this or justify the previous step?

**Comment by koriavinash1** [comment]
@charlio23, the last step is basically obtained from Jensen's inequality $f(\sum p x) \leq \sum pf(x)$, in case of iid samples it is trivially true.

**Comment by charlio23** [comment]
Oh, thanks that is clear. Do you think it would be helpful to add this clarification?
@koriavinash1  I sure think a clarification is needed, since the students might not be familiar with Jensen's inequality and thus might not find it trivial. 
@markvdw  what do you think about this?

**Comment by koriavinash1** [comment]
Yaa makes sense, will add a comment regarding this

**Comment by markvdw** [comment]
Thanks for discussing this.

Is there any way of avoiding using Jensen's inequality? We haven't really discussed that in the course yet. Is the sum of squares itself not equal to the estimate of the variance? Would substituting this not be an easier solution, if this showed that every element of the matrix was negative?

If this is the case, you do have a negative definite matrix.

**Comment by koriavinash1** [comment]
I think we can just use i.i.d assumption to completely remove that inequality as it's trivially satisfied as pointed out by @charlio23, which looks something like this:

$$ |H| = -\frac{N^2}{2 (\sigma^{2*})^3} + \frac{N}{(\sigma^{2*})^4} \sum_{i=1}^N (x_i - \mu^{*})^2 - \frac{1}{(\sigma^{2*})^4} (\sum_{i=1}^N(x_i - \mu^{*}))^2$$

$$ \Rightarrow |H| = -\frac{N^2}{2 (\sigma^{2*})^3} + \frac{N^2}{(\sigma^{2*})^4} \sum_{i=1}^N \frac{(x_i - \mu^{*})^2}{N} - \frac{1}{(\sigma^{2*})^4} (\sum_{i=1}^N(x_i - \mu^{*}))^2$$

$$ \Rightarrow |H| = \frac{N^2}{2 (\sigma^{2*})^3}  - \frac{1}{(\sigma^{2*})^4} (\sum_{i=1}^N(x_i - \mu^{*}))^2$$


$$ \Rightarrow |H| = \frac{N^2}{2 (\sigma^{2*})^3} \quad \quad (i.i.d \quad assumption)$$

$$ \Rightarrow |H| \geq 0$$

Let me know if this makes sense, I'll update in exercise.

**Comment by charlio23** [comment]
Yes, this looks fine! Feel free to close the issue when you pull the modification.
